#!/bin/bash
## run fdrc to all subfolders
## req. msslib

tmp=$(mktemp XXXXXXX.tmp)
find -type d | sed 's@\.\/@@g' >$tmp
curdir="$(dirs)"

for ((i=2;i<=$(wc -l $tmp | sed "s@ $tmp@@g");i++)); do
    cp -f msslib "$(head -n $i $tmp 2>&1 | tail -n 1)"/msslib
    cd "$(head -n $i $tmp 2>&1 | tail -n 1)"
    ./msslib fdrch+ '' '' '' '' '' f
    cd "$curdir"
    rm -f "$(head -n $i $tmp 2>&1 | tail -n 1)"/msslib
done
rm -f $tmp
