#!/bin/bash
## flac volume normalization
## Based on fdrc
## Req. ffmpeg. head. tail. wc
## There are no checks, so the probability of failure is high
## Use ./fvn
## Author Andrew S.
## Licence GPL
## https://github.com/quarkscript/media_works
findgain(){
                    ptmf=$(mktemp tmp.XXXXXXXXX)
                    ptmf1=$(mktemp tmp.XXXXXXXXX)
                    head -n $3 $2>$ptmf1
                    tail -n 1 $ptmf1>$ptmf
                    astream_id=$(cat $ptmf | sed 's\.*#0:\\g' | sed 's\: .*\\g')
                    astream_ch=$(cat $ptmf | sed 's\.*Hz, \\g' | sed 's\(.*\\g')
                    astream_fr=$(cat $ptmf | sed 's\ Hz.*\\g' | sed 's\.*, \\g')
                    astream_cod="flac -compression_level 8"
                    vol_up=$(ffmpeg -i "$1" -hide_banner -map 0:"$astream_id" -af "volumedetect" -f null /dev/null 2>&1 | grep max_volume | grep max_volume | grep -o -E "[-][0-9][0-9.][0-9 .][0-9 ]" | sed -e 's/-//g' | sed -e 's/ //g') 
                    if [ "$(echo $vol_up | sed -e 's/\.//g')" -gt "600" ]; then 
                        vol_up=60
                    fi
                    vol_up+=dB
                    echo "-c:a:$5 $astream_cod -ar $astream_fr -af volume=$vol_up ">>$4
                }
ffmproc(){
                    scr=$(mktemp tmp.XXXXXXXXX)
                    tmf=$(mktemp tmp.XXXXXXXXX)
                    script=""
                    ffmpeg -hide_banner -i "$1" 2>$tmf
                    script+="-map 0 -c copy "
                    echo $script>$scr
                    count=0
                    for i in $(cat $tmf | grep "Audio" -n | sed 's/:.*//g'); do
                        findgain "$1" "$tmf" "$i" "$scr" "$count"
                        count=$(($count+1))
                    done
                    script=$(echo $(cat $scr))
                    rm -f tmp.*
                    ffmpeg -i "$1" $script "$2$1" -hide_banner
                }
prefix="vn_"
fmts="flac"
lst=$(mktemp lst.XXXXXXXXX)
for i in $fmts; do
    find  -maxdepth 1 -not -name "$prefix*" -name "*.$i" | sed 's|\.\/||g'>>$lst
done
currfile=$(mktemp lst.XXXXXXXXX)
enf=$(wc -l $lst | sed 's/ lst.*//g')
for (( j=1; j<=$enf; j+=1)); do
    head -n $j $lst>$currfile
    inpar=$(tail -n 1 $currfile)
    ffmproc "$inpar" "$prefix"
done
rm -f lst.*

